# Generated by Django 6.0.4 on 2026-04-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='sales.bill'),
            preserve_default=False,
        ),
    ]
