# Generated by Django 6.0.4 on 2026-04-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='ist_paid',
            new_name='is_paid',
        ),
    ]
