# Generated by Django 6.0.4 on 2026-04-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_ist_paid_bill_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='newsletter',
            new_name='newsletter_abo',
        ),
    ]
